# Generated by Django 5.2.7 on 2025-11-11 22:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeployment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('base_height', models.FloatField()),
                ('antenna_height', models.FloatField()),
                ('original_position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'base_deployment',
            },
        ),
        migrations.CreateModel(
            name='BaseDeploymentFileType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_deployment_file_type',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'deployment',
            },
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gps',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, unique=True, upload_to='raster_upload')),
                ('size', models.IntegerField(default=0)),
                ('resolution', models.FloatField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('srid', models.IntegerField(default=0)),
                ('bands', models.IntegerField(default=0)),
                ('extent', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('tile_dir', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'raster',
            },
        ),
        migrations.CreateModel(
            name='RasterType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'raster_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Rpas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rpas',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyPointType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('marker_color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'survey_point_type',
            },
        ),
        migrations.CreateModel(
            name='BaseDeploymentFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='base_deployments')),
                ('note', models.TextField(blank=True, null=True)),
                ('base_deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.basedeployment')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.basedeploymentfiletype')),
            ],
            options={
                'db_table': 'base_deployment_file',
            },
        ),
        migrations.AddField(
            model_name='basedeployment',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deployment'),
        ),
        migrations.AddField(
            model_name='basedeployment',
            name='gps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.gps'),
        ),
        migrations.AddField(
            model_name='basedeployment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.person'),
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, unique=True, upload_to='contours')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('resolution', models.FloatField()),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.raster')),
            ],
            options={
                'db_table': 'contour',
            },
        ),
        migrations.AddField(
            model_name='raster',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.rastertype'),
        ),
        migrations.CreateModel(
            name='RpasFlight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('altitude', models.FloatField()),
                ('velocity', models.FloatField()),
                ('camera_mode', models.CharField(max_length=2)),
                ('aperture', models.CharField(blank=True, max_length=32, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=32, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('flight_path', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('flight_path_file', models.FileField(blank=True, null=True, upload_to='flight_paths')),
                ('plan_name', models.CharField(blank=True, max_length=64, null=True)),
                ('plan_geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('plan_file', models.FileField(blank=True, null=True, upload_to='plan_geometries')),
                ('home_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deployment')),
                ('rpas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.rpas')),
            ],
            options={
                'db_table': 'rpas_flight',
            },
        ),
        migrations.CreateModel(
            name='RasterRpasFlight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raster')),
                ('rpas_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rpasflight')),
            ],
            options={
                'db_table': 'raster_rpas_flight',
            },
        ),
        migrations.CreateModel(
            name='RpasFlightRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rpasflight')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.role')),
            ],
            options={
                'db_table': 'rpas_flight_role',
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.survey'),
        ),
        migrations.CreateModel(
            name='SurveyPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, null=True)),
                ('original_point', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('cd_point', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('base_deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.basedeployment')),
                ('survey_point_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.surveypointtype')),
            ],
            options={
                'db_table': 'survey_point',
            },
        ),
    ]
